/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package psksvp.jni.rpi;

public class PiSensors {
  public static boolean start() {
    return PiSensorsJNI.start();
  }

  public static void stop() {
    PiSensorsJNI.stop();
  }

  public static SensorData poll() {
    return new SensorData(PiSensorsJNI.poll(), true);
  }

}
